### ISSUE TITLE
connect failed

### ISSUE THREAD

**Issue by leecade** [CodeEffect/RemoteEdit#1]
osx 10.7 / sublime 3

```
MAIN 03:03:13: run ssh command called with cmd: "echo $SHELL; grep --version; ls --version"
MAIN 03:03:13: ....now on the queue.....
MAIN 03:03:13: Calling set_timeout to check for results
SSH[0] 03:03:13: Process not running: 'NoneType' object has no attribute 'poll'
Exception in thread Thread-8:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "/Library/Application Support/Sublime Text 3/Packages/RemoteEdit/remote_edit/RemoteEditConnectionWorker.py", line 73, in run
    self.process_work_and_respond()
  File "/Library/Application Support/Sublime Text 3/Packages/RemoteEdit/remote_edit/RemoteEditConnectionWorker.py", line 100, in process_work_and_respond
    self.work["accept_new_host"]
  File "/Library/Application Support/Sublime Text 3/Packages/RemoteEdit/remote_edit/RemoteEditConnectionWorker.py", line 135, in run_command
    if not self.connect(promptContains, acceptNew):
  File "/Library/Application Support/Sublime Text 3/Packages/RemoteEdit/remote_edit/RemoteEditConnectionWorker.py", line 180, in connect
    self.create_process()
  File "/Library/Application Support/Sublime Text 3/Packages/RemoteEdit/remote_edit/RemoteEditConnectionWorker.py", line 327, in create_process
    **kwargs
  File "X/subprocess.py", line 818, in __init__
  File "X/subprocess.py", line 1416, in _execute_child
PermissionError: [Errno 13] Permission denied

Traceback (most recent call last):
  File "/Library/Application Support/Sublime Text 3/Packages/RemoteEdit/RemoteEdit.py", line 3107, in <lambda>
    statusDir
  File "/Library/Application Support/Sublime Text 3/Packages/RemoteEdit/RemoteEdit.py", line 3092, in handle_callbacks
    {"success": False, "out": "", "err": ""}
  File "/Library/Application Support/Sublime Text 3/Packages/RemoteEdit/RemoteEdit.py", line 439, in handle_server_info
    shellVersion = results["out"].split("\n")[1].strip().split("/")[-1]
IndexError: list index out of range
```

**Comment by CodeEffect** [comment]
It was windows only until about 5 minutes ago :)

I've added Linux support and hopefully with that OSX should pretty much work too. I have no test machine for OSX though so any feedback on the new version would be greatly appreciated. 

I'll close this bug as invalid as the version you've tried didn't have any OSX support at all. If you could try the new version and report back your findings that would be fantastic. If you do find any bugs (quite likely I'm afraid) and can spare the time to do a little debugging you'd be welcome to email me on steve@codeeffect.co.uk or raise a bug if it's mainly working apart from some small issues. 

Either way, thank you for the report, let me know how you get on :)
